[package]
name = "myapp"
version = "0.1.0"
edition = "2021"

[dependencies]
rspring = { path = "../rspring" }
rspring_macro = { path = "../rspring_macro" }
axum = "0.8.7"
automod = "1.0.14"
tokio = { version = "1", features = ["full"] }
